---

- block:
  - name: install dependencies
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: no # skip cache check since we already ran apt
    with_items:
    - "{{ dependencies.encryption }}"

  - name: add dependencies to install list
    set_fact:
      install_packages: "{{ install_packages + dependencies['encryption'] }}"

  - name: set encryption targets (full device)
    set_fact:
      _encrypt_targets: "{{ _encrypt_targets|default({})|combine({item.device: item}) }}"
    with_items: "{{ layout }}"
    when: item.encrypt|default(False)

  - name: set encryption targets (partition)
    set_fact:
      _encrypt_targets: "{{ _encrypt_targets|default({})|combine({item.value['device']: item.value}) }}"
    with_dict: "{{ layout }}"
    when: item.value['encrypt']|default(False)

  - name: create encrypted devices
    shell: >
      echo '{{ item.value['passphrase'] }}' | cryptsetup -q --cipher {{ item.value['cipher']|default('aes-xts-plain64') }}
      --key-size {{ item.value['key-size']|default('256') }}  --hash {{ item.value['hash']|default('sha512') }}
      --iter-time {{ item.value['iter-time']|default('5000') }} luksFormat {{ item.key }}
    with_dict: "{{ _encrypt_targets|default({}) }}"

  - name: fetch luks UUID for device
    command: "cryptsetup luksUUID {{ item.key }}"
    register: _luksuuid
    with_dict: "{{ _encrypt_targets|default({}) }}"

  - name: store data for target devices
    set_fact:
      _tgt_devices: >
        {{ _tgt_devices|combine({item.stdout:
        item.item.value|combine({'device': '/dev/mapper/' +  item.item.value['target'], 'encrypt': None,
        'passphrase': None, 'target': None, 'use_dev': True})}) }}
    with_items: "{{ _luksuuid.results }}"

  - name: open luks Devices
    shell: >
      echo '{{ item.value['passphrase'] }}' |
      cryptsetup -q luksOpen {{ item.value['device'] }} {{ item.value['target'] }}
    with_dict: "{{ _encrypt_targets|default({}) }}"
    register: _luksopen

- rescue:
  - include: cleanup.yml
  - include: wipe.yml